name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: actions/setup-java@v1
      with:
      java-version: '17'
      distribution: 'adopt'
      cache: maven
    - name: Build with Maven
      run: mvn clean install
      
